@echo off
echo Starting Backend...
start "Backend Server" cmd /k "cd backend && python main.py"
echo Starting Frontend...
start "Frontend Client" cmd /k "cd frontend && npm run dev"
echo App started.
